# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo Ideas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photo Ideas
  pod "Moya"
  pod "Alamofire"
  pod "Argo"
  pod "Curry"
  pod "SwiftyCam"
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'SQLite.swift', '~> 0.11.3'

  target 'Photo IdeasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
